### ISSUE TITLE
Please provide an AppImage for download

### ISSUE THREAD

**Issue by probonopd** [rahmanshaber/corebox#1]
> We need to add package for this app.Appimage is in top priority.so if any one could guide us how to do that it will be helpful.

Can you get corebox to build on Ubuntu 14.04 (trusty) on [Travis CI](travis-ci.org) using [linuxdeployqt](https://github.com/probonopd/linuxdeployqt/) and Qt from https://launchpad.net/~beineri/+archive/ubuntu/opt-qt594-trusty similar to what is shown on https://github.com/probonopd/linuxdeployqt/blob/master/README.md#using-linuxdeployqt-with-travis-ci?

Please let me know if you are running into any issues.

**Comment by rahmanshaber** [comment]
where to write app name?

**Comment by rahmanshaber** [comment]
Please review the .travis.yml

**Comment by probonopd** [comment]
https://travis-ci.org/rahmanshaber/corebox/builds/348700469#L519 suggests that some more packages need to be installed in 

https://github.com/rahmanshaber/corebox/blob/master/.travis.yml#L11

 such as `qt59multimedia` and `qt59charts-no-lgpl`.

**Comment by rahmanshaber** [comment]
ok. latest build finds all the dependencies .
i don't understood the errors

**Comment by probonopd** [comment]
Latest error is:

```
corefm/mimeutils.cpp:22:19: fatal error: magic.h: No such file or directory
 #include <magic.h>
                   ^
compilation terminated.
```

Probably you need to install `libmagic-dev`in https://github.com/rahmanshaber/corebox/blob/master/.travis.yml#L11.

**Comment by rahmanshaber** [comment]
now what's the error ??

**Comment by probonopd** [comment]
https://travis-ci.org/rahmanshaber/corebox/builds/348888136#L861 suggests that `libpulse-dev` may be missing.

**Comment by rahmanshaber** [comment]
now now!!!
i build that in arch packaging it buid fine with icon error.
but package dose not have icon.

is my corebox.desktop has some problem??
could you see the error file??

**Comment by probonopd** [comment]
Great, it has been compiled successfully. Now, `CoreBox.desktop` needs some love:

* Value "Qt;Utility" for string list key "Categories" in group "Desktop Entry" does not have a semicolon (';') as trailing character --> End this line with a `;` character to fix this
* value "coreBox.svg" for key "Icon" in group "Desktop Entry" is an icon name with an extension, but there should be no extension as described in the Icon Theme Specification if the value is not an absolute path --> Remove the `.svg` from the `Icon=` line
* warning: value "" for key "Path" in group "Desktop Entry" does not look like an absolute path --> Remove the line starting with `Path=`

**Comment by rahmanshaber** [comment]
now good??

`[Desktop Entry]
GenericName=CoreBox
Type=Application
Name=CoreBox
Name[de]=CoreBox
Name[sr]=CoreBox
Name[sr@ijekavian]=CoreBox
Name[sr@latin]=CoreBox
Name[sr@ijekavianlatin]=CoreBox
Name[zh_TW]=CoreBox
Categories=Qt;Utility;
Name[en_US.utf8]=CoreBox

Comment=A bunch of common desktop application
Exec=coreBox
Icon=coreBox
Terminal=false
StartupNotify=false
`

**Comment by probonopd** [comment]
Looks about right, but to be sure please run it through the `desktop-file-validate` tool. (I am not in front of a Linux machine right now.)

**Comment by rahmanshaber** [comment]
is that an app??

**Comment by probonopd** [comment]
http://manpages.ubuntu.com/manpages/trusty/man1/desktop-file-validate.1.html

**Comment by rahmanshaber** [comment]
hurray build is finished successfully.
now where is the appimage?

**Comment by probonopd** [comment]
You need to tell the upload script to upload `CoreBox*.AppImage*` in

https://github.com/rahmanshaber/corebox/blob/67133de863effe299bdfc65fb78ed12194444a52/.travis.yml#L31

So, replace `APPNAME` with `CoreBox`.

**Comment by rahmanshaber** [comment]
any suggestion or example of upload.sh?
could i upload to google drive?
or email me the file?

**Comment by probonopd** [comment]
Please change the line from

`bash upload.sh APPNAME*.AppImage*`

to

`bash upload.sh CoreBox*.AppImage*`

This is all you need to change in `.travis.yml`.

**Comment by rahmanshaber** [comment]
where it uploaded after build?

**Comment by probonopd** [comment]
https://travis-ci.org/rahmanshaber/corebox/builds/348940295#L1136

For this to work, you need to enable Travis CI for your repository as [described here](https://travis-ci.org/getting_started), if you haven't already done so. Also, You need to set up `GITHUB_TOKEN` in Travis CI for this to work; please see https://github.com/probonopd/uploadtool. 

Once you have done that, it will show up on https://github.com/rahmanshaber/corebox/releases automatically after each `git push`.

It's really not hard to set up.

**Comment by rahmanshaber** [comment]
please review the 
https://github.com/rahmanshaber/corebox/blob/master/.travis.yml
please  i need the appimage badly.
thanks for the help.

**Comment by probonopd** [comment]
In the log file of the latest build I see:

> Setting environment variables from repository settings
$ export travis-ci=[secure]
The previous command failed, possibly due to a malformed secure environment variable.
Please be sure to escape special characters such as ' ' and '$'.
For more information, see https://docs.travis-ci.com/user/encryption-keys.

Please make sure that the token is entered correctly into Travis CI, especially there are not extra blanks at the beginning or the end (this happens frequently). Best delete the token and enter it again, making sure there are no blanks at the beginning or the end.

**Comment by rahmanshaber** [comment]
i don't think i will ever get there

**Comment by probonopd** [comment]
I think you are almost there, in fact. Only thing missing is the proper GitHub token in the Travis CI settings.

**Comment by probonopd** [comment]
Thanks for providing an AppImage. However, it likely was built on a too new version so that it refuses to run even on Ubuntu 16.04:

```
$ /home/me/Downloads/CoreBox-x86_64.AppImage
/home/me/Downloads/CoreBox-x86_64.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /tmp/.mount_CoreBousxMx2/lib/libQt5Core.so.5)
/home/me/Downloads/CoreBox-x86_64.AppImage: /lib/x86_64-linux-gnu/libz.so.1: version `ZLIB_1.2.9' not found (required by /tmp/.mount_CoreBousxMx2/lib/libpng16.so.16)
/home/me/Downloads/CoreBox-x86_64.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /tmp/.mount_CoreBousxMx2/lib/libsystemd.so.0)
```

Please build on the oldest still-supported version of Ubuntu LTS, which is currently 14.04, thanks.

Reference:
https://github.com/AppImage/appimage.github.io/pull/449

**Comment by rahmanshaber** [comment]
thank for the information.
i chose apppimage because for dependencies problem.but what i am seeing
here is making me mad.
why the appimage is not including all this package?? any thing configure
that i missed??
i will try to make an appimage in ubuntu 18.04 when it release.
i want the latest qt for my app . so i think 18.04 will be the right
platform.

**Comment by probonopd** [comment]
Please build on the oldest still-supported version of Ubuntu LTS, which is currently 14.04, thanks.

> why the appimage is not including all this package??

While in theory you could bundle _everything_ inside an AppImage, most people choose to _not_ bundle basic system libraries that can be expected to be present on each target system (in order to get smaller AppImages and have less duplication of code). But this means that you need to compile on the oldest still-supported target system, because a Linux application can generally run on newer, but not on older systems than the one the application was compiled for. See https://en.wikipedia.org/wiki/Backward_compatibility

> i want the latest qt for my app . so i think 18.04 will be the right
platform.

No. Please always use the _oldest still-supported_ Ubuntu version, which is 14.04 at the moment. There is the latest Qt 5.9.x available for it as described in https://github.com/probonopd/linuxdeployqt/

**Comment by rahmanshaber** [comment]
thanks.
i will build the newer version in ubuntu 14.04.
another thing i have ask.
is there any way to set the font of the app?? i saw in appimage font is not
same as my build one.

**Comment by probonopd** [comment]
> is there any way to set the font of the app?? i saw in appimage font is not
same as my build one.

Do you mean the fonts from the Gtk+ theme with the "correct" fonts?

**Comment by rahmanshaber** [comment]
yes

**Comment by probonopd** [comment]
This used to work in older Qt versions, but at least the more recent builds don't do this anymore. We are aware of the issue but don't have the solution yet, see https://github.com/AppImage/AppImages/issues/88. This is not limited to AppImage but a more general Qt question.
